sudo: required
dist: trusty
language: ruby
addons:
  apt:
    packages:
      - tesseract-ocr
rvm:
 - 2.1
 - 2.2
cache: bundler
before_script:
  - cp .travis.env .env
  - mkdir -p public/ocr-uploads
  - mkdir -p public/ocr-output
script:
  - bundle exec rake
