source 'https://rubygems.org'


gem 'thin'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'rack-flash3'
gem 'rack-test'
gem 'encrypted_cookie'
gem 'mini_magick'
gem 'rtesseract', github: 'abarrak/rtesseract', branch: 'add-pdf-support'
gem 'i18n'
gem 'erubis'
gem 'mail'
gem 'prawn'
gem 'arabic-letter-connector'
gem 'rufus-scheduler'
gem 'fastimage'
gem 'recaptcha'
gem 'dotenv'
gem 'puma'
gem 'aws-sdk', '~> 2'
